### ISSUE TITLE
Miscellaneous minor comments

### ISSUE THREAD

**Issue by ghost** [CefasRepRes/Git_Training#4]
The early, hurried test of `git init`, `git add` etc before that was explained caused quite a lot of confusion. Can I suggest that `git --version` is probably enough until all that stuff is properly explained?

The "Staging area" is referred to as the "index" in the documentation. Might be worth making that clear?

It's a common convention that commit messages should be in the present tense "Add new script" rather than "Added new script".

I would prefer it if we toned down the "do not store data". GitHub is great for small to medium CSV files and we use that extensively on the Salmon project.

Git commit messages can be long - I have seen short essays. The important thing is that the first line should be a short summary.

We could be clearer about the nature of the SHA-1 commit hashes - that they are globally unique names, they are not random, they are based on the content of the diff and the parent pointer and they are key to allowing Git to be a distributed system.

Should we talk about `rebase` and `cherry pick` towards te end? People can be very anal about the commit history on main. Some shops don't like seeing merge commits on main and expect them to be cleaned up with a rebase or avoided by using a cherry pick instead of merge.

Suggest numbering the slides for easy reference

One slide suggested avoid using git pull? I avoid those problems with `git config --global pull.rebase true` and I honestly think it should be the default

Could we use `git log --graph` to illustrate a bit more about divergent branches?

**Comment by tiagoams** [comment]
### On Staging area/index
In lesson 2 I have replaced **Staging index** by **Staging area** as I think this is easier to associate with an _outbox_ of files to be included in the next commit. 
I suggest that we refer to **Staging area** throughout the course.

@jenniferagraham I have added a Note in your slide 20 of session 1 saying:
Note: the Staging area is often called the index in git outputs.
Please see if you want to include this.

### Commit messages in present tense
This is pain to change in some slides, but will make sure to do this in live examples.

### Slide numbering
Done!

**Comment by tiagoams** [comment]
### rebase, cherry pick
I have learned  more about rebase and can see how rebasing instead of merging a branch keeps a more logical history and how rebase with squash gives the opportunity to document branches better. Still this seems too advanced for an introductory course. Ditto for cherry pick wich I have never used.

### avoid pull, pull --rebase
Slide S3-19 teaches **fetch, merge(or pull)** but I don't think that we still advise somwhere against using pull.

I would need to test out in practive if we should be teaching `git pull --rebase` as a way to avoid timing issues and if this better and still safe. 

Do you have different opinions?

**Comment by jenniferagraham** [comment]
These have now been reviewed.  

#### On Staging area/index

Happy with the updates made. Will note this in Session 1 intro. 

#### Data

I've rephrased S1-48 to try and clarify use for large vs small data files. Main message is that GitHub shouldn't be seen to replace previous data archives (e.g., Cefas Data Hub, BODC etc.). However, agree that it is useful for managing changes. 

#### Commit messages

Agree. For brevity vs detail, I will include this in discussion on the day (rather than making slides more detailed). 

#### pull vs fetch/merge

I've rephrased the slides in S3 to avoid any impression that people shouldn't use pull. 

#### rebase, cherry-pick etc. 

I agree that this is perhaps a bit more advanced, and time is limited. 

I have used cherry-pick, but only once or twice. This is probably less common than needing to revert vs reset, so suggest people can look this up as/when needed (like I did)!
